#application:  balmy-curve-149710
#version: 1
runtime: python27
api_version: 1
threadsafe: true

balmy-curve-149710:asia-east1:chatbook-sql

handlers:
- url: /
  static_files: FRONTEND/index.html
  upload: FRONTEND\/index.html
- url: /API/getRoomList
  script: BACKEND.getRoomList
- url: /API/getUsersInRoom
  script: BACKEND.getUsersInRoom
- url: /API/getRoomChat
  script: BACKEND.getRoomChat
- url: /API/sendChat
  script: BACKEND.sendChat
- url: /API/changeRoom
  script: BACKEND.changeRoom
- url: /API/registerUser
  script: BACKEND.registerUsero

libraries:
- name: MySQLdb
  version: "latest"

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: balmy-curve-149710:asia-east1:chatbook-sql
    CLOUDSQL_USER: chatuser
    CLOUDSQL_PASSWORD: chatuser
# [END env_variables]
