#application:  balmy-curve-149710
#version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: FRONTEND/index.html
  upload: FRONTEND/index.html
- url: /API/getRoomList
  script: BACKEND.getRoomList
- url: /API/getUsersInRoom
  script: BACKEND.getUsersInRoom
- url: /API/getRoomChat
  script: BACKEND.getRoomChat
- url: /API/sendChat
  script: BACKEND.sendChat
- url: /API/changeRoom
  script: BACKEND.changeRoom
- url: /API/registerUser
  script: BACKEND.registerUser
